### ISSUE TITLE
Port Australia transformations to master/QGIS3

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/naturalgis_ntv2_transformations#25]
@alexgleith

**Comment by alexgleith** [comment]
Hey @gioman, I've got the dev (master) version of QGIS for mac now. Says version 2.99. Is this the version that will be 3.0 that I should be testing against?

**Comment by gioman** [comment]
@alexgleith 

> Hey @gioman, I've got the dev (master) version of QGIS for mac now. Says version 2.99. Is this the version that will be 3.0 that I should be testing against?

yes. probably in 

https://github.com/NaturalGIS/ntv2_transformations/blob/master/metadata.txt

you will need to change the minimum version to 2.99, because as it is now it won't show/work.
