### ISSUE TITLE
Can this be deployed to the QGIS 3 plugin repo?

### ISSUE THREAD

**Issue by alexgleith** [NaturalGIS/naturalgis_ntv2_transformations#34]
I just searched in QGIS 3, and can't see the plugin in the list.

Has it been deployed? If not, can we deploy it? I'm hoping to merge the Australian transforms into the master branch now.

**Comment by gioman** [comment]
@alexgleith will work on this matter next week.

**Comment by alexgleith** [comment]
Great news, @gioman.

Which branch should I be setting up a PR to get the Aussie ones in for v3?

**Comment by gioman** [comment]
Finally ported.
