### ISSUE TITLE
Help missing

### ISSUE THREAD

**Issue by pcav** [NaturalGIS/naturalgis_ntv2_transformations#4]
Unclear how to use it

**Comment by eggnog-armed** [comment]
Hi gioman

I like your ferret / polecat profile photo!

Can you or anyone say quickly how to use this?

I've installed the plugin.

I have some files I would like to reproject with the best available transformations.

This appears on opening the project. https://i.imgur.com/9b4kIGH.jpg

Thanks

**Comment by gioman** [comment]
> Unclear how to use it

the plugin was downloaded ~36000 times with no complains about it, we can safely close.

**Comment by gioman** [comment]
> Hi gioman
> 
> I like your ferret / polecat profile photo!
> 
> Can you or anyone say quickly how to use this?
> 
> I've installed the plugin.
> 
> I have some files I would like to reproject with the best available transformations.
> 
> This appears on opening the project. https://i.imgur.com/9b4kIGH.jpg
> 
> Thanks

@ayounggun the plugin works as an addon for the Processing toolbox. is not meant to reproject on the fly layers using ntv2 grids, something that QGIS 3 nows does it out of the box (the dialog you attached, which also guides you to download some packages containing ntv2 grids which may not be shipped by default with QGIS).

The plugin goal was always to allow the user create copies of vector/raster data reprojecting them using ntv2 transformations. Of course as Processing runs also in batch mode this is very hand for who (for example) needs move on from a old CRS to  a new one and has the opportunity to use a ntv2 grid to do the operation. New ntv2 based transformation must be added manually, see the README for a list of the transformations supported at the moment.
